---
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code using cargo fmt.
        entry: cargo fmt --all
        language: system
        files: \.rs$
        args: ["--"]
  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.1.1
    hooks:
      - id: cargo-check
      - id: clippy
