---
name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: juancarlosjr97/github-actions-workflows-to-rule-them-all/.github/workflows/shared-rust-tests.yml@4523b68e32fbf8f1940e2e5d54a568712ca25cda # 0.7.7
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
