---
name: Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: juancarlosjr97/github-actions-workflows-to-rule-them-all/.github/workflows/shared-rust-tests.yml@c00a8ea3194ea9cbe256369f305d94571285a639 # 0.7.12
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
